baseURL = 'https://laboratorij-km.github.io/'
languageCode = 'en-us'
title = 'LKM site'
theme = "site-theme"
paginate = 3
[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "People"
    pageRef = "/people/"
    weight = 2
  [[menu.main]]
    name = "Research"
    pageRef = "/research/research/"
    weight = 3
  [[menu.main]]
    name = "Teaching"
    pageRef = "/teaching/"
    weight = 4
  [[menu.main]]
    name = "Links"
    pageRef = "/links/"
    weight = 5
  [[menu.main]]
    name = "Photos"
    pageRef = "/photos/"
    weight = 6


  

