baseURL = 'https://laboratorij-km.github.io/'
languageCode = 'en-us'
title = 'LKM site'
theme = "site-theme"
relativeURLs = true
paginate = 3
[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 100
    identifier = "about"  
  
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 101
    parent = "about"  

  [[menu.main]]
    name = "Presentations"
    url = "/about/presentations/"
    parent = "about"  
    weight = 102

  [[menu.main]]
    name = "Location"
    url = "/about/location/"
    parent = "about"  
    weight = 103

  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 200
  
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 300
    identifier = "research"  

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 301
    parent = "research"  

  [[menu.main]]
    name = "Collaboration"
    url = "/research/collaboration/"
    parent = "research"  
    weight = 302
  
  [[menu.main]]
    name = "Guests"
    url = "/research/guests/"
    parent = "research"
    weight = 303

  [[menu.main]]
    name = "Projects"
    url = "/research/projects/"
    parent = "research"
    weight = 304

  [[menu.main]]
    name = "Selected References"
    url = "/research/selected_references/"
    parent = "research"
    weight = 305

  [[menu.main]]
    name = "MLDM book"
    url = "http://mldmbook.fri.uni-lj.si/"
    parent = "research"
    weight = 306
  
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 400

  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 500

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 600


  

